# Generated by Django 5.0.2 on 2024-02-15 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='films',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmsapp.films', verbose_name='Фільм'),
        ),
    ]
